### ISSUE TITLE
Load model error

### ISSUE THREAD

**Issue by emigmo** [ac-93/tactile_gym#1]
download the model files and load to evaluation env...

> pybullet build time: Nov 26 2020 23:09:05
Loaded EGL 1.5 after reload.
GL_VENDOR=NVIDIA Corporation
GL_RENDERER=GeForce RTX 2080/PCIe/SSE2
GL_VERSION=4.6.0 NVIDIA 460.80
GL_SHADING_LANGUAGE_VERSION=4.60 NVIDIA
Version = 4.6.0 NVIDIA 460.80
Vendor = NVIDIA Corporation
Renderer = GeForce RTX 2080/PCIe/SSE2
ven = NVIDIA Corporation
ven = NVIDIA Corporation
Traceback (most recent call last):
  File "demo_trained_agents.py", line 48, in <module>
    final_evaluation(
  File "/home/robot/anaconda3/envs/robel/lib/python3.8/site-packages/tactile_gym-0.0.1-py3.8.egg/tactile_gym/sb3_helpers/eval_agent_utils.py", line 112, in final_evaluation
    model = sb3.PPO.load(model_path)
  File "/home/robot/anaconda3/envs/robel/lib/python3.8/site-packages/stable_baselines3-1.1.0a11-py3.8.egg/stable_baselines3/common/base_class.py", line 650, in load
    data, params, pytorch_variables = load_from_zip_file(path, device=device, custom_objects=custom_objects)
  File "/home/robot/anaconda3/envs/robel/lib/python3.8/site-packages/stable_baselines3-1.1.0a11-py3.8.egg/stable_baselines3/common/save_util.py", line 402, in load_from_zip_file
    data = json_to_data(json_data, custom_objects=custom_objects)
  File "/home/robot/anaconda3/envs/robel/lib/python3.8/site-packages/stable_baselines3-1.1.0a11-py3.8.egg/stable_baselines3/common/save_util.py", line 164, in json_to_data
    deserialized_object = cloudpickle.loads(base64_object)
AttributeError: Can't get attribute '_make_cell' on <module 'cloudpickle.cloudpickle' from '/home/robot/anaconda3/envs/robel/lib/python3.8/site-packages/cloudpickle/cloudpickle.py'>
Destroy EGL OpenGL window.

**Comment by emigmo** [comment]
Update cloudpickle version to 1.6.0 would be work
