### ISSUE TITLE
connection reset by peer

### ISSUE THREAD

**Issue by yuxwen** [ac-93/tactile_gym#13]
Loaded EGL 1.4 after reload.Unable to create EGL context(eglError:12292)Traceback(most recent call last):File "train agent.py", line 113,in <module>train agent(File "train agent.py", line 41,in train agentenv = make training envs(env id, env args, rl params, save dir)File "/home/ubuntu1804/tactile_gym/tactile_ gym/sb3 helpers/rl utils.py", line15,in make training envs
env = make vec env
File "/home/ubuntu1804/anaconda3/envs/python38/lib/python3.8/site-packages/stable baselines3/common/env util.py", line 105, in make vec envreturn vec_env_cls([make env(i + start index)for i in range(n envs)], **vecenv kwargs)File "/home/ubuntu1804/anaconda3/envs/python38/lib/python3.8/site-packages/stable baselines3/common/vec _env/subproc_vec_env.py", line 111,in _initobservation space, action space = self.remotes[0].recv()File "/home/ubuntu1804/anaconda3/envs/python38/lib/python3.8/multiprocessing/c
onnection.py"，line 250，inrecvbuf = self. recv bytes()File "/home/ubuntu1804/anaconda3/envs/python38/lib/python3.8/multiprocessing/connection.py",line 414,in recv bytesbuf = self. recv(4)File "/home/ubuntu1804/anaconda3/envs/python38/lib/python3.8/multiprocessing/connection.py",line 379,in recv
chunk = read(handle,remaining)ConnectionResetError:[Errno 104]connection reset by peer

**Comment by yuxwen** [comment]
Compile failed:
0:1(10): error: GLSL 1.50 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.00 ES, and 3.00 ES

Warning/Error in GLSL shader:
error: vertex shader lacks `main'

Warning/Error in GLSL shader:
error: vertex shader lacks `main'

Warning/Error in GLSL shader:
error: vertex shader lacks `main'

Warning/Error in GLSL shader:
error: vertex shader lacks `main'

Warning/Error in GLSL shader:
error: vertex shader lacks `main'

Warning/Error in GLSL shader:
error: vertex shader lacks `main'

GL error 0x501 detected in glGenBuffers
ven = Mesa/X.org
ven = Mesa/X.org
Traceback (most recent call last):
File "/home/ros2/miniconda3/tactile_gym_push/tactile_gym/sb3_helpers/train_agent.py", line 184, in
train_agent(
File "/home/ros2/miniconda3/tactile_gym_push/tactile_gym/sb3_helpers/train_agent.py", line 52, in train_agent
env = make_training_envs(
File "/home/ros2/miniconda3/tactile_gym_push/tactile_gym/sb3_helpers/rl_utils.py", line 16, in make_training_envs
env = make_vec_env(env_id,
File "/home/ros2/miniconda3/envs/python39/lib/python3.9/site-packages/stable_baselines3/common/env_util.py", line 105, in make_vec_env
return vec_env_cls([make_env(i + start_index) for i in range(n_envs)], **vec_env_kwargs)
File "/home/ros2/miniconda3/envs/python39/lib/python3.9/site-packages/stable_baselines3/common/vec_env/subproc_vec_env.py", line 111, in init
observation_space, action_space = self.remotes[0].recv()
File "/home/ros2/miniconda3/envs/python39/lib/python3.9/multiprocessing/connection.py", line 250, in recv
buf = self._recv_bytes()
File "/home/ros2/miniconda3/envs/python39/lib/python3.9/multiprocessing/connection.py", line 414, in _recv_bytes
buf = self._recv(4)
File "/home/ros2/miniconda3/envs/python39/lib/python3.9/multiprocessing/connection.py", line 379, in _recv
chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
ven = Mesa/X.org

I am running the code on Ubuntu installed through a virtual machine. I wonder if this has any impact.
