### ISSUE TITLE
Pix

### ISSUE THREAD

**Issue by dljzx** [ac-93/tactile_gym#6]

**Comment by dljzx** [comment]
Nice work of your tactile gym! But real to sim translation using pix2pix is not concluded in your code. Can you share your real world dataset and code? Thank you so much

**Comment by ac-93** [comment]
Thanks for the kind words!

We are currently looking at the best way to release the tactile datasets and should hopefully be able to get this out soon. At the same time we will open another repo that contains the second part of the code used for sim2real transfer, including the pix2pix GAN. For reference we based this pix2pix implementation off of the pytorch implementation available [here](https://github.com/eriklindernoren/PyTorch-GAN/tree/master/implementations/pix2pix).

I'll leave this issue open and will update again when we release everything!

**Comment by kimsekeun** [comment]
I cannot find rl_parms.json in saved_models. could you upload that?

**Comment by yuxwen** [comment]
Compile failed:
0:1(10): error: GLSL 1.50 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.00 ES, and 3.00 ES

Warning/Error in GLSL shader:
error: vertex shader lacks `main'

Warning/Error in GLSL shader:
error: vertex shader lacks `main'

Warning/Error in GLSL shader:
error: vertex shader lacks `main'

Warning/Error in GLSL shader:
error: vertex shader lacks `main'

Warning/Error in GLSL shader:
error: vertex shader lacks `main'

Warning/Error in GLSL shader:
error: vertex shader lacks `main'

GL error 0x501 detected in glGenBuffers
ven = Mesa/X.org
ven = Mesa/X.org
Traceback (most recent call last):
File "/home/ros2/miniconda3/tactile_gym_push/tactile_gym/sb3_helpers/train_agent.py", line 184, in
train_agent(
File "/home/ros2/miniconda3/tactile_gym_push/tactile_gym/sb3_helpers/train_agent.py", line 52, in train_agent
env = make_training_envs(
File "/home/ros2/miniconda3/tactile_gym_push/tactile_gym/sb3_helpers/rl_utils.py", line 16, in make_training_envs
env = make_vec_env(env_id,
File "/home/ros2/miniconda3/envs/python39/lib/python3.9/site-packages/stable_baselines3/common/env_util.py", line 105, in make_vec_env
return vec_env_cls([make_env(i + start_index) for i in range(n_envs)], **vec_env_kwargs)
File "/home/ros2/miniconda3/envs/python39/lib/python3.9/site-packages/stable_baselines3/common/vec_env/subproc_vec_env.py", line 111, in init
observation_space, action_space = self.remotes[0].recv()
File "/home/ros2/miniconda3/envs/python39/lib/python3.9/multiprocessing/connection.py", line 250, in recv
buf = self._recv_bytes()
File "/home/ros2/miniconda3/envs/python39/lib/python3.9/multiprocessing/connection.py", line 414, in _recv_bytes
buf = self._recv(4)
File "/home/ros2/miniconda3/envs/python39/lib/python3.9/multiprocessing/connection.py", line 379, in _recv
chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
ven = Mesa/X.org

I am running the code on Ubuntu installed through a virtual machine. I wonder if this has any impact.

**Comment by ryandongpc** [comment]
Could I ask if there is any update about the code and dataset? Thanks!

**Comment by ryandongpc** [comment]
Could I ask if there is any update about the pix2pix code and dataset? Thanks!
